### ISSUE TITLE
xchainpy_thorchain: python-binance-chain missing dependancy

### ISSUE THREAD

**Issue by dylmanning** [xchainjs/xchainpy-lib#68]
I am unsure whether it is required to install python-binance-chain or not (possibly unmaintained as it will not install) or if there is an alternative library?

However is there a workaround to access xchainpy_thorchain/crypto.py?

**ModuleNotFoundError: No module named 'binance_chain.utils**

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from xchainpy_thorchain.client import Client
  File "/Users/dylan/Projects/mccn_arb/env/lib/python3.7/site-packages/xchainpy_thorchain/client.py", line 12, in <module>
    from . import crypto
  File "/Users/dylan/Projects/mccn_arb/env/lib/python3.7/site-packages/xchainpy_thorchain/crypto.py", line 3, in <module>
    from binance_chain.utils.segwit_addr import address_from_public_key, decode_address, bech32_decode
ModuleNotFoundError: No module named 'binance_chain.utils'`

**Comment by hoodieonwho** [comment]
simply change binance_chain to py_binance_chain would resolve this issue.
py_binance_chain is an improved version of binance_chain which requires less packages
